version: '3.1'

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=DAONode

  redis:
    image: redis:6.2-alpine
    restart: always

  mongo:
    image: mongo:4.2.13-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

#  AWS-CLI
