name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'master'
      tag_suffix:
        description: 'Optional suffix for the Docker tag (e.g., dev, test)'
        required: false
        default: ''

jobs:
  build-and-push:
    name: Build and Publish Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: docker_tags
        run: |
          # Sanitize branch name by replacing '/' with '-'
          BRANCH_TAG=$(echo "${{ github.event.inputs.branch }}" | tr '/' '-')
          if [ -n "${{ github.event.inputs.tag_suffix }}" ]; then
            echo "tags=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}-${{ github.event.inputs.tag_suffix }},ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${BRANCH_TAG}-${{ github.event.inputs.tag_suffix }}" >> $GITHUB_OUTPUT
          else
            echo "tags=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${BRANCH_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}
